server:
  rootPath: /API/*
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9000 
  adminConnectors:
      - type: http
        port: 8081

logging:
  loggers:
    org.glassfish.jersey.filter.LoggingFilter: ERROR
